# -*- coding: utf-8 -*-
"""week 1.ipynb UPDATED at 7.12.2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Caw6e69LX_Wowvj4jcKll156WHPIMHNp
"""





#### Course: Python ####
#### Subject: Week 1 assignment ####
#### Written by: Maya Poches id 315114744 ####

"""Imports"""

import pandas as pd
import random

"""Variables & Constants"""

participants_num = 6
gender_list = ["female", "male"]

"""Main Code"""

age_list = []
depression_list = []

for i in range(participants_num):
    random_age = random.randint(15, 40)
    age_list.append(random_age)
    random_status = random.randint(0, 1)
    depression_list.append(random_status)


data_dict = {"index": list(range(1,participants_num + 1)),
             "gender": list(random.choices(gender_list, k=participants_num)),
             "age": age_list,
             "depression": depression_list}

participants_df = pd.DataFrame(data_dict)

print(participants_df)
participants_df.to_csv("Week 1 sample.csv")